function ccv = inty_buttons(ccv)


binning_controls = figure('name', 'Controls', 'NumberTitle', 'off');



text1 = uicontrol('Parent', binning_controls, 'style','text', ...
    'Position', [10 390 100 20], ...
    'String', 'Low D_{iso}');
slider_low_diso = uicontrol('Parent', binning_controls, 'Style', 'slider',...
    'Min', -11, 'Max', -8, 'Value',-11,...
    'Position', [10 375 100 20],...
    'Tag', 'diso_low_slider',...
    'UserData', struct('diso_low', -11),...
    'Callback', @slider_diso_low);

text2 = uicontrol('Parent', binning_controls, 'style','text', ...
    'Position', [10 340 100 20], ...
    'String', 'High D_{iso}');
slider_high_diso = uicontrol('Parent', binning_controls, 'Style', 'slider',...
    'Min', -11, 'Max', -8, 'Value',-8,...
    'Position', [10 325 100 20],...
    'Tag', 'diso_high_slider',...
    'UserData', struct('diso_high', -8),...
    'Callback', @slider_diso_high);

text3 = uicontrol('Parent', binning_controls, 'style','text', ...
    'Position', [10 290 100 20], ...
    'String', 'Low D_{ratio}');
slider_low_dratio = uicontrol('Parent', binning_controls, 'Style', 'slider',...
    'Min', -3, 'Max', 3, 'Value', -3,...
    'Position', [10 275 100 20],...
    'Tag', 'dratio_low_slider',...
    'UserData', struct('dratio_low', -3),...
    'Callback', @slider_dratio_low);

text4 = uicontrol('Parent', binning_controls, 'style','text', ...
    'Position', [10 240 100 20], ...
    'String', 'High D_{ratio}');
slider_high_dratio = uicontrol('Parent', binning_controls, 'Style', 'slider',...
    'Min', -3, 'Max', 3, 'Value', 3,...
    'Position', [10 225 100 20],...
    'Tag', 'dratio_high_slider',...
    'UserData', struct('dratio_high', 3),...
    'Callback', @slider_dratio_high);

text5 = uicontrol('Parent', binning_controls, 'style','text', ...
    'Position', [10 190 100 20], ...
    'String', 'Low R_{2}');
slider_low_r2 = uicontrol('Parent', binning_controls, 'Style', 'slider',...
    'Min', -0.5, 'Max', 2, 'Value', -0.5,...
    'Position', [10 175 100 20],...
    'Tag', 'r2_low_slider',...
    'UserData', struct('r2_low', -0.5),...
    'Callback', @slider_r2_low);

text6 = uicontrol('Parent', binning_controls, 'style','text', ...
    'Position', [10 140 100 20], ...
    'String', 'High R_{2}');
slider_high_r2 = uicontrol('Parent', binning_controls, 'Style', 'slider',...
    'Min', -0.5, 'Max', 2, 'Value', 2,...
    'Position', [10 125 100 20],...
    'Tag', 'r2_high_slider',...
    'UserData', struct('r2_high', 2),...
    'Callback', @slider_r2_high);


button = uicontrol('Parent', binning_controls, 'Style', 'pushbutton',...
    'Position', [10 100 100 20], ...
    'String', 'Show limits',...
    'Callback', @button_callback);

end


function slider_diso_low(hObject, eventdata)
    diso_low = hObject.Value;
    data = struct('diso_low', diso_low);
    hObject.UserData = data;
end

function slider_diso_high(hObject, eventdata)
    diso_high = hObject.Value;
    data = struct('diso_high', diso_high);
    hObject.UserData = data;
end

function slider_dratio_low(hObject, eventdata)
    dratio_low = hObject.Value;
    data = struct('dratio_low', dratio_low);
    hObject.UserData = data;
end

function slider_dratio_high(hObject, eventdata)
    dratio_high = hObject.Value;
    data = struct('dratio_high', dratio_high);
    hObject.UserData = data;
end

function slider_r2_low(hObject, eventdata)
    r2_low = hObject.Value;
    data = struct('r2_low', r2_low);
    hObject.UserData = data;
end

function slider_r2_high(hObject, eventdata)
    r2_high = hObject.Value;
    data = struct('r2_high', r2_high);
    hObject.UserData = data;
end


function button_callback(hObject, eventdata)
    diso_low = findobj('Tag', 'diso_low_slider');
    diso_high = findobj('Tag', 'diso_high_slider');
    dratio_low = findobj('Tag', 'dratio_low_slider');
    dratio_high = findobj('Tag', 'dratio_high_slider');
    r2_low = findobj('Tag', 'r2_low_slider');
    r2_high = findobj('Tag', 'r2_high_slider');
    
    data1 = diso_low.UserData;
    data2 = diso_high.UserData;
    data3 = dratio_low.UserData;
    data4 = dratio_high.UserData;
    data5 = r2_low.UserData;
    data6 = r2_high.UserData;
    
    display([data1.diso_low data2.diso_high data3.dratio_low data4.dratio_high data5.r2_low data6.r2_high])
    
    
end